---
abstract: 'CHI Driver for Redis'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Class: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CHI-Driver-Redis
no_index:
  directory:
    - inc
    - t
requires:
  CHI: 0
  Moose: 0
  Redis: 0
  Try::Tiny: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
